# https://github.com/openscript/openscript 를 참고하였습니다 !

on:
  issue_comment:
    types: [created, edited, deleted]

name: Guestbook

jobs:
  update_guestbook:
    name: Update guestbook
    if: ${{ github.event.issue.title == 'Guestbook' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Update guestbook from comments
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |

            const query = `query($owner:String!, $name:String!, $issue_number:Int!) {
              repository(owner:$owner, name:$name){
                issue(number:$issue_number) {
                  comments(first:5,orderBy:{direction:DESC, field:UPDATED_AT}) {
                    nodes {
                      author {
                        avatarUrl(size: 30)
                        login
                        url
                      }
                      url
                      bodyText
                      updatedAt
                    }
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              issue_number: context.issue.number
            }

            const result = await github.graphql(query, variables);
            const comments = result.repository.issue.comments.nodes;
            let totalText  ='<table align="center" height="250">';
            totalText += comments.reduce((prev, curr) => {
                const author = curr.author.url
                const avatarUrl = curr.author.avatarUrl;
                let text = curr.bodyText;
                const who = curr.author.login;
                if(text.length>20) text = text.slice(0,20) +".....";
                return `${prev}<tr><td> <a href="${author}"><img width="30" src="${avatarUrl}"/></a></td><td><p align="center">${who}</p></td><td><p align="center">${text}</p></td></tr>`;
              }, "");

            totalText+= "</table></p></td></table>";
            const fileSystem = require('fs');
            const readme = fileSystem.readFileSync('./README.md', 'utf8');
            fileSystem.writeFileSync('./README.md', readme.replace(/(?<=<!-- Guestbook -->.*\n)[\S\s]*?(?=<!-- \/Guestbook -->|$(?![\n]))/gm, totalText), 'utf8');
            const test = fileSystem.readFileSync('./README.md', 'utf8');
            console.log(test);
      - name: Push guestbook update
        run: |
          git config --global user.name 'jungmin'
          git config --global user.email '1232132+JEM1224@users.noreply.github.com'
          git commit -am '방명록 업데이트  ! '
          git push